apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-usage
  namespace: openshift-kube-apiserver
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  groups:
    - name: pre-release-lifecycle
      rules:
        - alert: APIRemovedInNextReleaseInUse
          annotations:
            message: >-
              Deprecated API that will be removed in the next version is being used. Removing the workload that is using
              the {{$labels.group}}.{{$labels.version}}/{{$labels.resource}} API might be necessary for
              a successful upgrade to the next cluster version.
              Refer to the apirequestcount.apiserver.openshift.io resources to identify the workload.
          expr: |
            group(apiserver_requested_deprecated_apis{removed_release="1.22"}) by (group,version,resource) and (sum by(group,version,resource) (rate(apiserver_request_total[4h]))) > 0
          for: 1h
          labels:
            severity: info
        - alert: APIRemovedInNextEUSReleaseInUse
          annotations:
            message: >-
              Deprecated API that will be removed in the next EUS version is being used. Removing the workload that is using
              the {{"{{$labels.group}}"}}.{{"{{$labels.version}}"}}/{{"{{$labels.resource}}"}} API might be necessary for
              a successful upgrade to the next EUS cluster version.
              Refer to the apirequestcount.apiserver.openshift.io resources to identify the workload.
          expr: |
            group(apiserver_requested_deprecated_apis{removed_release=~"1\\.2[123]"}) by (group,version,resource) and (sum by(group,version,resource) (rate(apiserver_request_total[4h]))) > 0
          for: 1h
          labels:
            severity: info
