apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-apiserver-requests
  namespace: openshift-kube-apiserver
spec:
  groups:
    - name: apiserver-requests-in-flight
      rules:
        # We want to capture requests in-flight metrics for kube-apiserver and openshift-apiserver.
        # apiserver='kube-apiserver' indicates that the source is kubernetes apiserver.
        # apiserver='openshift-apiserver' indicates that the source is openshift apiserver.
        # The subquery aggregates by apiserver and request kind. requestKind is {mutating|readOnly}
        # The following query gives us maximum peak of the apiserver concurrency over a 2-minute window.
        - record: cluster:apiserver_current_inflight_requests:sum:max_over_time:2m
          expr: |
            max_over_time(sum(apiserver_current_inflight_requests{apiserver=~"openshift-apiserver|kube-apiserver"}) by (apiserver,requestKind)[2m:])
