apiVersion: v1
kind: ConfigMap
metadata:
  name: csr-controller-ca
  namespace: openshift-config-managed
data:
  ca-bundle.crt: |
    {{ .Assets | load "kube-ca.crt" | indent 4 }}
    {{ .Assets | load "kubelet-signer.crt" | indent 4 }}
