apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-server-ca
  namespace: openshift-config-managed
data:
  ca-bundle.crt: |
    {{ .Assets | load "kube-apiserver-complete-client-ca-bundle.crt" | indent 4 }}

