apiVersion: v1
kind: Secret
metadata:
  name: aggregator-client
  namespace: openshift-kube-apiserver
  annotations:
    "auth.openshift.io/certificate-not-before": {{ .Assets | load "apiserver-proxy.crt" | notBefore }}
    "auth.openshift.io/certificate-not-after": {{ .Assets | load "apiserver-proxy.crt" | notAfter }}
    "auth.openshift.io/certificate-issuer": {{ .Assets | load "apiserver-proxy.crt" | issuer }}
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "apiserver-proxy.crt" | base64 }}
  tls.key: {{ .Assets | load "apiserver-proxy.key" | base64 }}
